version: '3.9'

services:
  smoking_api:
    build: .
    command: sh -c "alembic upgrade head && python run_server.py"
    env_file:
      ./.env.dev
    depends_on:
      - database
    ports:
      - '8000:8000'
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=mio_client
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=mio_statistic
volumes:
  postgres_data:
