version: '3.9'

services:
  smoking_api:
    build: .
    command: sh -c " python run_server.py"
    depends_on:
      - database
    ports:
      - '8000:8000'
  database:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
